### PR TITLE
Iterate on CSS styling

### PR DESCRIPTION
**Pull request by NoelFB**
This is a small pass on the CSS styling. I'm not sure if you are looking for contributions to the style right now but I thought I'd commit and see!

### CODE REVIEW

**Comment by icculus** [comment]
I totally missed this PR because you had the misfortune to submit it _the day we started on SDL3_, so my notifications were a flood. I'll take a look shortly!

**Comment by NoelFB** [comment]
Haha totally understandable! Obviously no rush at all, appreciate you taking a look and seeing if it fits the direction/style.

**Comment by icculus** [comment]
...and then I forgot this existed again, despite cursing the existing CSS daily.   :( 

Sorry, Noel. Can I extract anything useful from this still? Or just replace the current stuff wholesale with it?

**Comment by NoelFB** [comment]
Oh, no worries at all Ryan! I was looking at the recently merged #56 and felt it hit most of the stuff I was trying to do at the time :) It may be fun to do another pass based on the current version so if I get some time I'll definitely submit more changes!

**Pull request closed without merging**
